[main]
    separator = "-"
    description = "PyLadies Vancouver"
    enableDarkMode = true
    enableLanguageSelectionStorage = true
    modes = ["light", "dark"]
    canonifyAssetsURLs = false
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    titleCase = true
    [main.internalLinks]
        validate = true
        pretty = true
    [main.externalLinks]
        cue = true
        tab = true
    [main.build]
        transpiler = "dartsass"
        silenceDeprecations = true

[debugging]
    showJS = false
    showSCSS = false
    purgeHTMLComments = true # prevents a Goldmark warning when processing HTML comments (as used by markdownlint)
    includeSVGOrigin = true

#[docs]
#    basePath = "/" # TODO: replace
#    github = "https://github.com/gethinode/hinode"
#    release = "https://github.com/gethinode/hinode/releases/tag/"
#    checkVersion = false

[home]
    sections = ["get_involved"]
    fullCover = true
    centerHeadline = true
    style = ""
    [home.feature]
        orientation = "stacked"
        color = "primary"
        width = 6
        align = "start"

[navigation]
    anchor = true
    logo = "/img/pyladiesvancouver-square-logo.png"
    color = "body"
    fixed = true
    overlay = false
    overlayMode = "dark"
    horizontal = false
    offset = "5.5rem"
    offsetXS = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"

[messages]
    placement = "bottom-right"

[dam]
    dimensions = "dimensions.yml"
    videoCodecs = [
        "webm/vp9",
        "mp4/h265",
        "mp4"
    ]

[[dam.providers]]
    name = "Cloudinary"
    pattern = "cloudinary"
    adapter = "assets/adapters/cloudinary.html"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

[sections]
#    [sections.blog]
#        title = "Blog"
#        sort = "date"
#        reverse = true
#        cols = 3
#        color = ""
#        padding = "0"
#        header = "full"
#        footer = "none"
#        orientation = "stacked"
#        style = "border-0 card-zoom card-body-margin"
#        homepage = 3
#        separator = true
    [sections.get_involved]
        title = "Get Involved with our Community"
        sectionHeader = "justify-content-end"
        layout = "card"
        sort = "weight"
        reverse = false
        background = "body-tertiary"
        color = "body"
        style = "justify-content-center"
        cols = 3
        padding = "3"
        header = "none"
        footer = "none"
        orientation = "stacked"
        homepage = 3

[favicon]
    logo = "img/pyladiesvancouver-logo.png"
    sizes = [16, 32, 48]

# toml-docs-start theme-colors
[style]
    primary = "#fa023c"
    secondary = "#c8102e"
    tertiary = "#fa023c"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#142a36"
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
    themeFont = "Inter"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" # external path
    themeFontPath = "/fonts" # local path
    themeFontPreload = "/fonts/inter-v12-latin-regular.woff2"
    purge = true
# toml-docs-end theme-colors
#
[schema]
    type = "Organization"
    name = "PyLadies Vancouver"
    locale = "en-US"
    # twitter = "https://twitter.com/gethinode"
    # linkedIn = ""
    github = "https://github.com/pyladies-vancouver/pyladies-vancouver.github.io"
    section = "blog"
    [schema.author]
        name = "PyLadies Vancouver"
        # twitter = "https://twitter.com/markdumay"
        linkedin = "https://www.linkedin.com/company/pyladies-vancouver/"
        github = "https://github.com/pyladies-vancouver"
    [schema.logo]
        url = "img/pyladiesvancouver-logo.png"
        width = 512
        height = 512
    [schema.image]
        url = "img/pyladiesvancouver-hero-img.png"
        width = 1280
        height = 640

[opengraph]
    images = ["img/pyladiesvancouver-square-logo.png"]
    locale = "en_US"

#[links]
#    bs_badge_heading = "https://getbootstrap.com/docs/5.3/components/badge/#headings"
#    hinode_docs = "https://gethinode.com"
#    hugo_imaging = "https://gohugo.io/content-management/image-processing/#imaging-configuration"
#    mozilla_image = "https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images"
#    observatory = "https://observatory.mozilla.org/analyze/demo.gethinode.com"
#    pagespeed = "https://pagespeed.web.dev/report?url=https%3A%2F%2Fdemo.gethinode.com%2F"
#    hinode = "https://gethinode.com"

[modules.cookieyes]
    url = "https://cdn-cookieyes.com/client_data/537760a88a9e93feaccdbfc1/script.js"

# toml-docs-start headers
[headers]
  [headers.netlify]
    source = "netlify.toml"
# toml-docs-end headers

# toml-docs-start csp
[modules.hinode.csp]
    style-src = ["www.youtube.com"]
    font-src = ["fonts.gstatic.com"]
    frame-src = [
        "player.cloudinary.com",
        "www.youtube-nocookie.com",
        "www.youtube.com",
        "app.netlify.com",
        "www.canva.com",
        "drive.google.com"
    ]
    img-src = [
        "data:",
        "*.imgix.net",
        "*.imagekit.io",
        "*.cloudinary.com",
        "i.ytimg.com",
        "www.netlify.com"
    ]